import Head from "next/head";
import DashboardLayout from "../../Components/Dashboard/DashboardLayout";
import AllEventsForm from "../../Components/OrganizerDashboard/AllEvents/AllEventsForm";
import SearchEvent from "../../Components/OrganizerDashboard/AllEvents/SearchEvent";

export default function allEvents() {
    return (
        <div className="allevents-wrapper">
            <h2 className="header border-0 p-0">View Events | All Events</h2>
            <Head>
                <title>Create Next App</title>
                <meta name="create event" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SearchEvent />
            <AllEventsForm />
        </div>
    )
}

allEvents.Layout = DashboardLayout