

import Head from "next/head";
import DashboardLayout_F from "../../Components/Dashboard/DashboardLayout_F";
import EditEvent from "../../Components/OrganizerDashboard/CreateEvent/EditEvent";

export default function editEvent() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="create event" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <EditEvent />
        </>
    )
}

editEvent.Layout = DashboardLayout_F