import Head from "next/head";
import DashboardLayout_D from "../../Components/Dashboard/DashboardLayout_D";
import OrganizerSetting from "../../Components/OrganizerDashboard/OrganizerSetting";

export default function index() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="events" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <OrganizerSetting />


        </>
    )
}

index.Layout = DashboardLayout_D