import Head from "next/head";
import EventBanner_C from "../Components/Events/EventBanner_C";
import EventsContent_C from '../Components/Events/EventsContent_C';
import Footer  from '../Layouts/Footer';

export default function eventList() {
    return (
        <div className="events-wrapper">
            <Head>
                <title>Create Next App</title>
                <meta name="events" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <EventBanner_C />
            <EventsContent_C />
            <Footer/>

        </div>
    )
}