import Head from "next/head";
import EventsBanner_B from '../Components/Events/EventsBanner_B';
import EventsContent_B from '../Components/Events/EventsContent_B';
import Footer  from '../Layouts/Footer';

export default function Events_B() {
    return (
        <div className="events-wrapper">
            <Head>
                <title>Create Next App</title>
                <meta name="events" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <EventsBanner_B />
            <EventsContent_B />
            <Footer/>
            

        </div>
    )
}