import Head from 'next/head' 
import Banner from '../Components/Home/Banner';
import styles from '../styles/Home.module.css' 
import Concept from '../Components/Home/Concept';
import HowItWorks from '../Components/Home/HowItWorks';
import Events from '../Components/Home/Events';
import Venue from '../Components/Home/Venue';
import MiSocial from '../Components/Home/MiSocial';
import EventOrganizer from '../Components/Home/EventOrganizer';
import FooterBanner from '../Components/Home/FooterBanner';
import Footer  from '../Layouts/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Banner/>
       <Concept/>
       <HowItWorks/>
       <Events/>
       <Venue/>
       <MiSocial/>
       <EventOrganizer/>
       <FooterBanner/>
       <Footer/>
    </div>
  )
}
