import { Form, FormControl, Modal } from "react-bootstrap";

import Head from 'next/head' 
import Banner_B from '../Components/Home/Banner_B';
import styles from '../styles/Home.module.css' 
import Concept from '../Components/Home/Concept';
import HowItWorks from '../Components/Home/HowItWorks';
import HowItWorksAfterlogin from '../Components/Home/HowItWorksAfterlogin';

import Events from '../Components/Home/Events';
import Venue from '../Components/Home/Venue';
import MiSocial from '../Components/Home/MiSocial';
import EventOrganizer from '../Components/Home/EventOrganizer';
import EventOrganizerAfterlogin from '../Components/Home/EventOrganizerAfterlogin';
import FooterBanner from '../Components/Home/FooterBanner';
import Footer  from '../Layouts/Footer';
import Banner_afterlogin from '../Components/Home/Banner_afterlogin';

export default function IndexB() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
       {/* <Banner_B/> */}
       <Banner_afterlogin/>
       <Concept/>
       {/* <HowItWorks/> */}
       <HowItWorksAfterlogin/>
       <Events/>
       <Venue/>
       <MiSocial/>
       <EventOrganizerAfterlogin/>
       {/* <FooterBanner/>  */}
        <FooterBanner/>
       <Footer/>
    </div>
  )
}
