import Head from "next/head";
import Footer from '../Layouts/Footer';
import OrganizerTermsBanner from '../Components/OrganizerTermsConditions/OrganizerTermsBanner';
import OrganizerTermsConditions from '../Components/OrganizerTermsConditions/OrganizerTermsConditions';

export default function OrganizerTerms() {
    return (
        <div className="terms-main-wr">
            <Head>
                <title>Create Next App/organizer-terms-conditions
                </title>
                <meta name="sign up next" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <OrganizerTermsBanner />
            <OrganizerTermsConditions />
            <Footer />
        </div>
    )
}