import Head from "next/head";
import FormSection from "../Components/Signup-stepone/FormSection";
import SignupOnebanner from "../Components/Signup-stepone/SignupStepBanner";
import Modal from 'react-bootstrap/Modal';
import Button from 'react-bootstrap/Button';
import Image from "next/image";
import successTick from '../public/images/successTick.png';
import { useState } from "react";
import FooterBanner from '../Components/Home/FooterBanner';
import Footer  from '../Layouts/Footer';
 

export default function SignupOne() {
  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);
  return (
    <div  className="signup-step-oneWrapper">
      <Head>
        <title>Create Next App</title>
        <meta name="Sign up step 1" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignupOnebanner />
      <FormSection/>

      {/* <Modal.Dialog show={show} onHide={handleClose} className="universalModal forgetModal1">
            <Modal.Header closeButton>
            </Modal.Header>
              <Modal.Body>
                  <div className="successReset-modal">
                      <div className="text-center">
                          <Image src={successTick} alt="successTick"/>
                          <p>We've sent you an email on how to reset your password. 
              In the next 24 hours open the email and follow the steps outlined to create a new password.</p>
              <button className="btn btn-next">Click Here To Return To Our Home Page</button>
                      </div>
                  </div>
              </Modal.Body>
      </Modal.Dialog> */}

<Footer/>
    </div>
  )
}