import Head from "next/head";
import DashboardLayout from "../../Components/Dashboard/DashboardLayout";
import DeleteAccount from "../../Components/Dashboard/DeleteAccount/DeleteAccount";

export default function index() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="delete account" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DeleteAccount />
        </>
    )
}

index.Layout = DashboardLayout