import Head from "next/head";
import DashboardHome from "../../Components/Dashboard/DashboardHome";
import DashboardLayout from "../../Components/Dashboard/DashboardLayout";

export default function index() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="events" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardHome />
        </>
    )
}

index.Layout = DashboardLayout