import Head from "next/head";
import DashboardLayout_afterlogin from "../../Components/Dashboard/DashboardLayout_afterlogin";
import MyProfile from "../../Components/Dashboard/MyProfile/MyProfile";

export default function myProfile() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="events" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MyProfile />
        </>
    )
}

myProfile.Layout = DashboardLayout_afterlogin